---
title: "Model Between-Participant Baseline Predictors of Missing Data"
output: html_document
date: "2022-08-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Matrix)
library(dbplyr)
library(tidyverse)
library(lubridate)
library(lme4)
library(mice)
library(gghalves)
library(emmeans)
library(naniar)
library(broom.mixed)
library(lmerTest)
library(scales)
library(brms)
theme_set(theme_bw())

# Functions for running many models in this script
source('model_wrapper_functions.R')
options(buildtools.check = function(action) TRUE)
```


```{r}
load('../../cleaned_data/cleaned_data_for_daily_models.rda')
load('../../cleaned_data/cleaned_baseline_data.rda')
```

## For multiple comparisons correction, get # of clinical predictors (15)
```{r}
m = length(clinical_predictors)
corrected_conf_level = 1- (0.05/m)
```

## Set up daily data (up to day 200, participants finishing study)
```{r}
daily = left_join(daily, self_report_baseline, by = 'ID')
daily = dplyr::filter(daily, day_num <= 200)
daily = dplyr::filter(daily, TIMEPNT==6)
```


# Weekly risk data
```{r}
load('../../cleaned_data/risk.rda')

risk_missing = risk_week_present %>%
  dplyr::filter(week_num <= 28, days ==7) %>%
  group_by(ID) %>%
  mutate(personal_time_z = scale(week_num),
         summerbreak = month %in% c(7, 8),
         site = ifelse(startsWith(ID, '1'), 'CUIMC', 'UPMC'),
         siteCUMC = site == 'CUIMC') %>%
  ungroup() %>%
  left_join(., self_report_baseline, by = 'ID') 

risk_missing = dplyr::filter(risk_missing, TIMEPNT==6)
```

# Model Formulae

## Clinical variable model templates
```{r}
# remove interview date from sociodemographic predictors in models
sociodemographic_predictors = sociodemographic_predictors[!grepl('interview_date_numeric', sociodemographic_predictors)]

m_formula_template_gps = as.formula(paste('missing_gps ~ scaled_predictor + personal_time_z + weekend + summerbreak +', 
                                          paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_formula_template_accel = as.formula(paste('missing_accel ~ scaled_predictor + personal_time_z + weekend + summerbreak +', 
                                          paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_formula_template_keyboard = as.formula(paste('missing_keyboard ~ scaled_predictor + personal_time_z + weekend + summerbreak +', 
                                          paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_formula_template_daily = as.formula(paste('missing_daily ~ scaled_predictor + personal_time_z + weekend + summerbreak +', 
                                            paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_formula_template_risk = as.formula(paste('risk_missing ~ scaled_predictor + personal_time_z + summerbreak +', 
                                           paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))
```

## Sociodemographic models
```{r}
m_sociodemographic_daily = as.formula(paste('missing_daily ~ personal_time_z + weekend + summerbreak +', 
                                            paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_sociodemographic_gps = as.formula(paste('missing_gps ~ personal_time_z + weekend + summerbreak +', 
                                          paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_sociodemographic_accel = as.formula(paste('missing_accel ~ personal_time_z + weekend + summerbreak +', 
                                          paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_sociodemographic_keyboard = as.formula(paste('missing_keyboard ~ personal_time_z + weekend + summerbreak +', 
                                          paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))

m_sociodemographic_risk = as.formula(paste('risk_missing ~ personal_time_z + summerbreak +', 
                                           paste(sociodemographic_predictors, collapse = '+'), ' + (1 |ID)'))
```


# Run models & get ORs for each outcome

```{r risk_models}
risk_outputs = or_pipeline(df = risk_missing, 
                      model_formula_template = m_formula_template_risk,
                      clinical_predictors = clinical_predictors,
                      conf_level_corrected = corrected_conf_level,
                      bayes=TRUE)

# Save and clear unused memory
save(risk_outputs, file = 'model_outputs/baseline_predictors_missingness_brm_risk.rda')
rm(risk_outputs)
gc()
```

```{r daily_models}
daily_outputs = or_pipeline(df = daily, 
                      model_formula_template = m_formula_template_daily,
                      clinical_predictors = clinical_predictors,
                      conf_level_corrected = corrected_conf_level,
                      bayes=TRUE)

# Save and clear unused memory
save(daily_outputs, file = 'model_outputs/baseline_predictors_missingness_brm_daily.rda')
rm(daily_outputs)
gc()
```

```{r gps_models}
gps_outputs = or_pipeline(df = daily, 
                      model_formula_template = m_formula_template_gps,
                      clinical_predictors = clinical_predictors,
                      conf_level_corrected = corrected_conf_level,
                      bayes=TRUE)

# Save and clear unused memory
save(gps_outputs, file = 'model_outputs/baseline_predictors_missingness_brm_gps.rda')
rm(gps_outputs)
gc()
```

```{r accel_models}
accel_outputs = or_pipeline(df = daily, 
                      model_formula_template = m_formula_template_accel,
                      clinical_predictors = clinical_predictors,
                      conf_level_corrected = corrected_conf_level,
                      bayes=TRUE)

# Save and clear unused memory
save(accel_outputs, file = 'model_outputs/baseline_predictors_missingness_brm_accel.rda')
rm(accel_outputs)
gc()
```



```{r keyboard_models}
keyboard_outputs = or_pipeline(df = daily, 
                      model_formula_template = m_formula_template_keyboard,
                      clinical_predictors = clinical_predictors,
                      conf_level_corrected = corrected_conf_level,
                      bayes=TRUE)

save(keyboard_outputs, file = 'model_outputs/baseline_predictors_missingness_brm_keyboard.rda')
rm(keyboard_outputs)
gc()
```


# Sociodemographic models 
```{r}
# Models
gps_sociodem_model_brm = baseline_sociodemographic_model_with_missingness_brm(model_formula = m_sociodemographic_gps, df = daily)
accel_sociodem_model_brm = baseline_sociodemographic_model_with_missingness_brm(model_formula = m_sociodemographic_accel, df = daily)
keyboard_sociodem_model_brm = baseline_sociodemographic_model_with_missingness_brm(model_formula = m_sociodemographic_keyboard, df = daily)
daily_sociodem_model_brm = baseline_sociodemographic_model_with_missingness_brm(model_formula = m_sociodemographic_daily, df = daily)
risk_sociodem_model_brm = baseline_sociodemographic_model_with_missingness_brm(model_formula = m_sociodemographic_risk, df = risk_missing)

# Extract OR
daily_sociodem_or_brm = baseline_sociodemographic_model_odds_ratio(daily_sociodem_model_brm, type = 'Daily Mood Survey', 
                                                              conf_level_corrected = corrected_conf_level,
                                                              bayes=TRUE)
gps_sociodem_or_brm = baseline_sociodemographic_model_odds_ratio(gps_sociodem_model_brm, type = 'GPS', 
                                                              conf_level_corrected = corrected_conf_level,
                                                              bayes=TRUE)
risk_sociodem_or_brm = baseline_sociodemographic_model_odds_ratio(risk_sociodem_model_brm, type = 'Weekly SI Survey', 
                                                              conf_level_corrected = corrected_conf_level,
                                                              bayes=TRUE)
keyboard_sociodem_or_brm = baseline_sociodemographic_model_odds_ratio(keyboard_sociodem_model_brm, type = 'Keyboard Input',
                                                               conf_level_corrected = corrected_conf_level,
                                                              bayes=TRUE)
accel_sociodem_or_brm = baseline_sociodemographic_model_odds_ratio(accel_sociodem_model_brm, type = 'Accelerometer', 
                                                               conf_level_corrected = corrected_conf_level,
                                                              bayes=TRUE)

# Combine
combined_sociodem_or_brm = rbind(gps_sociodem_or_brm, 
                                 accel_sociodem_or_brm, 
                                 keyboard_sociodem_or_brm, 
                                 daily_sociodem_or_brm, 
                                 risk_sociodem_or_brm)

# Save outputs for compiling stats/plotting
save(gps_sociodem_model_brm, 
     accel_sociodem_model_brm, 
     keyboard_sociodem_model_brm, 
     daily_sociodem_model_brm, 
     risk_sociodem_model_brm, 
     combined_sociodem_or_brm, 
     file = 'model_outputs/sociodemographic_predictors_missingness_brm.rda')
```